src/TLAB/LouvreBundle/Entity/Booking.php
<?php

namespace TLAB\LouvreBundle\Entity;

use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;
use TLAB\LouvreBundle\Validator\IsOpenDay;
use TLAB\LouvreBundle\Validator\IsBookableDay;
use TLAB\LouvreBundle\Validator\CheckForTodayType;

/**
 * Booking
 *
 * @ORM\Table(name="booking")
 * @ORM\Entity(repositoryClass="TLAB\LouvreBundle\Repository\BookingRepository")
 */
class Booking
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="email", type="string", length=255)
     *
     * On vérifie que le champ n'est pas vide
     * @Assert\NotBlank(message="L'adresse e-mail ne peut être vide")
     *
     * On vérifie que nous recevons bien une adresse e-mail
     * @Assert\Email(message="Le format de votre adresse e-mail est incorrect")
     */
    private $email;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date", type="date")
     *
     * On vérifie que le champ n'est pas vide
     * @Assert\NotBlank()
     *
     * On vérifie que nous recevons bien une date
     * @Assert\Date()
     *
     * On vérifie que la date sélectionnée est supèrieure ou égale à la date du jour
     * @Assert\GreaterThanOrEqual("today", message="La date ne peut être antérieure à celle d'aujourd'hui")
     *
     * On vérifie que le musée est ouvert pour le jour sélectionné
     * Le musée est fermé tous les mardi ainsi que les 1er mai, 1er novembre et 25 décembre
     * @IsOpenDay()
     *
     * On vérifie que le jour sélectionné est "Réservable"
     * Les jours non réservables sont les dimanches et jours fériés non listé dans la validation précédente
     * @IsBookableDay()
     */
    private $date;

    /**
     * @var int
     *
     * @ORM\Column(name="type", type="integer")

     * On vérifie que le champ n'est pas vide
     * @Assert\NotBlank()
     */
    private $type;

    /**
     * @ORM\OneToMany(targetEntity="TLAB\LouvreBundle\Entity\People", mappedBy="booking", cascade={"persist"})
     * @Assert\Count(
     *      min = 1,
     *      max = 1000,
     *      minMessage = "Votre commande doit concerner au moins une personne",
     *      maxMessage = "Vous ne pouvez pas réserver plus de {{ limit }} places en une seule commande"
     * )
     * @Assert\Valid()
     */
    private $peoples;

    /**
     * @var string
     *
     * @ORM\Column(name="token", type="string", length=255, nullable=true)
     */
    private $token;


    /**
     * Constructor
     */
    public function __construct()
    {
        $this->peoples = new \Doctrine\Common\Collections\ArrayCollection();
        date_default_timezone_set('Europe/Paris');
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set email
     *
     * @param string $email
     *
     * @return Booking
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set date
     *
     * @param \DateTime $date
     *
     * @return Booking
     */
    public function setDate($date)
    {
        $this->date = $date;

        return $this;
    }

    /**
     * Get date
     *
     * @return \DateTime
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * Set type
     *
     * @param integer $type
     *
     * @return Booking
     */
    public function setType($type)
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Get type
     *
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }


    /**
     * Add people
     *
     * @param \TLAB\LouvreBundle\Entity\People $people
     *
     * @return Booking
     */
    public function addPeople(\TLAB\LouvreBundle\Entity\People $people)
    {
        $this->peoples[] = $people;

        return $this;
    }

    /**
     * Remove people
     *
     * @param \TLAB\LouvreBundle\Entity\People $people
     */
    public function removePeople(\TLAB\LouvreBundle\Entity\People $people)
    {
        $this->peoples->removeElement($people);
    }

    /**
     * Get peoples
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getPeoples()
    {
        return $this->peoples;
    }

    /**
     * Get Number Of Peoples
     *
     * @return integer
     */
    public function getNumberOfPeoples()
    {
        return $this->peoples->count();
    }

    /**
     * Get total price
     *
     * @return integer
     */
    public function getTotalPrice()
    {
        $price = 0;

        foreach ($this->peoples as $people) {
            $price += $people->getPrice();
        }


        return $price;
    }

    /**
     * Si le jour selectionné est aujourd'hui et qu'il est plus de 14h
     * Alors le type de billet doit être demi-journée
     * @Assert\Callback
     */
    public function isGoodTypeForTodayPM(ExecutionContextInterface $context)
    {
        $now = new \DateTime("now"); // On récupère le DateTime actuel
        $pm = 14; // A partir de 14h on ne peut plus réserver de billet journée complète

        // Si la date sélectionnée dans le formulaire est aujourd'hui
        if($this->date->format('d/m/y') === $now->format('d/m/y') ) {

            // Si l'heure actuelle est 14H00 ou plus
            if($now->format('H') >= $pm) {

                // Si le type de billet est journée complète
                if($this->type == '1') {

                    // Alors on déclenche une erreur
                    $context
                        ->buildViolation('La matinée est déja passée pour aujourd\'hui. Veuillez sélectionner des billets demi-journée.')
                        ->atPath('type')
                        ->addViolation()
                    ;
                }
            }
        }
    }

    /**
     * Set token
     *
     * @param string $token
     *
     * @return Booking
     */
    public function setToken($token)
    {
        $this->token = $token;

        return $this;
    }

    /**
     * Get token
     *
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }
}

src/TLAB/LouvreBundle/Form/BookingType.php
<?php

namespace TLAB\LouvreBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BookingType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('email', EmailType::class)
            ->add('date', DateType::class, [
                'widget'    => 'single_text'
            ])
            ->add('type', ChoiceType::class, [
                'choices'=> [
                    'Journée complète'  => '1',
                    'Demi-Journée'      => '2',
                ],
            ])
            ->add('peoples', CollectionType::class, [
                'entry_type' => PeopleType::class,
                'allow_add' => true,
                'allow_delete' => true,
                'prototype'    => 'TLABLouvreBundle:People:prototype.html.twig',
            ])
            ->add('submit', SubmitType::class)
        ;
    }
    
    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'TLAB\LouvreBundle\Entity\Booking'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'booking';
    }


}

src/TLAB/LouvreBundle/Controller/BookingController.php
<?php

namespace TLAB\LouvreBundle\Controller;

use Stripe\Charge;
use Stripe\Error\Card;
use Stripe\Stripe;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use TLAB\LouvreBundle\Entity\Booking;
use TLAB\LouvreBundle\Entity\Paiement;
use TLAB\LouvreBundle\Entity\People;
use TLAB\LouvreBundle\Form\BookingType;
use TLAB\LouvreBundle\Form\PaiementType;
use TLAB\LouvreBundle\Form\PeopleType;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

use Swift_Message;

use TLAB\LouvreBundle\Validator\hasLowerThanThousandPeoples;


class BookingController extends Controller
{
    /**
     *
     * Affiche le formulaire de réservation et gère quand il est envoyé
     *
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function bookingAction(Request $request)
    {
        $validator = $this->get('validator');


        // On créé une entité Booking
        $booking = new Booking();
        // On crée le formulaire associé à Booking
        $form = $this->get('form.factory')->create(BookingType::class, $booking);

        $formError = '';

        // On récupère la requête lorsque le formulaire est posté
        $form->handleRequest($request);
        // Si les champs du formulaire sont valides
        if($form->isSubmitted() && $form->isValid()) {

            $nbrPeoplesForThisDate = 0;

            // On récupère toutes les commandes pour la date sélectionnée
            $repo = $this->getDoctrine()->getRepository('TLABLouvreBundle:Booking');
            $bookingsForThisDate = $repo->findBy([ 'date'=>$booking->getDate() ]);

            // On additionne toutes les personnes de chaque commande pour cette journée
            foreach ($bookingsForThisDate as $curr_booking) {
                if(!empty($curr_booking->getToken())) {
                    $nbrPeoplesForThisDate += $curr_booking->getNumberOfPeoples();
                }

            }

            // Si le nombre de personnes pour cette journée + le nombre de personnes de la commande dépasse la limite on déclenche une erreur
            $contrainst = new hasLowerThanThousandPeoples($nbrPeoplesForThisDate);
            $formError = $validator->validate($booking->getNumberOfPeoples(), $contrainst);

            // Si il n'y a pas eu d'erreur on enregistre la nouvelle commande
            if(count($formError) === 0) {
                $em = $this->getDoctrine()->getManager();

                $em->persist($booking);

                foreach ($booking->getPeoples() as $people) {
                    $people->setBooking($booking);
                    $em->persist($people);
                }

                $em->flush();

                return $this->redirectToRoute('tlab_louvre_confirm', ['id'=>$booking->getId()]);
            }


        }

        return $this->render('TLABLouvreBundle:Booking:booking.html.twig', [
            'form'  => $form->createView(),
            'errors'    => $formError
        ]);
    }

    /**
     *
     * Permet de modifier une réservation
     *
     * @param $id
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function editBookingAction($id, Request $request)
    {
        $validator = $this->get('validator');
        $repo = $this->getDoctrine()->getRepository('TLABLouvreBundle:Booking');

        // On créé une entité Booking
        $booking = $repo->find($id);
        // On crée le formulaire associé à Booking
        $form = $this->get('form.factory')->create(BookingType::class, $booking);
        $formError = '';

        // On récupère la requête lorsque le formulaire est posté
        $form->handleRequest($request);
        // Si les champs du formulaire sont valides
        if($form->isSubmitted() && $form->isValid()) {

            $limit = 0;
            $nbrPeoplesForThisDate = 0;

            // On récupère toutes les commandes pour la date sélectionnée
            $bookingsForThisDate = $repo->findBy([ 'date'=>$booking->getDate() ]);

            // On additionne toutes les personnes de chaque commande pour cette journée
            foreach ($bookingsForThisDate as $curr_booking) {
                if(!empty($curr_booking->getToken())) {
                    $nbrPeoplesForThisDate += $curr_booking->getNumberOfPeoples();
                }

            }

            // Si le nombre de personnes pour cette journée + le nombre de personnes de la commande dépasse la limite on déclenche une erreur
            $contrainst = new hasLowerThanThousandPeoples($nbrPeoplesForThisDate);
            $formError = $validator->validate($booking->getNumberOfPeoples(), $contrainst);

            // Si il n'y a pas eu d'erreur on enregistre la nouvelle commande
            if(count($formError) === 0) {
                $em = $this->getDoctrine()->getManager();

                $peopleRepo = $em->getRepository('TLABLouvreBundle:People');
                $storredPeoples = $peopleRepo->findBy(['booking'=>$booking]);

                foreach ($storredPeoples as $people) {
                    $em->remove($people);
                }

                $em->persist($booking);

                foreach ($booking->getPeoples() as $people) {
                    $people->setBooking($booking);
                    $em->persist($people);
                }

                $em->flush();

                return $this->redirectToRoute('tlab_louvre_confirm', ['id'=>$booking->getId()]);
            }


        }

        return $this->render('TLABLouvreBundle:Booking:booking.html.twig', [
            'form'  => $form->createView(),
            'errors'    => $formError
        ]);
    }

    /**
     * Permet de généré le résumé de la commande et gère le paiement via stripe
     *
     * @param $id
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function confirmAction($id, Request $request)
    {
        // On récupère toutes les commandes pour la date sélectionnée
        $repo = $this->getDoctrine()->getRepository('TLABLouvreBundle:Booking');
        $booking = $repo->find($id);

        // Pour chaque People, on définit le type de billet en fonction de celui du booking (pour calculer le prix de chaque personne)
        foreach ($booking->getPeoples() as $people) {
            $people->setType($booking->getType());
        }


        $paiement = new Paiement();
        // On crée le formulaire associé à Booking
        $form = $this->get('form.factory')->create(PaiementType::class, $paiement);

        $form->handleRequest($request);

        if( $form->isSubmitted() ) {

            if($form->isValid()) {

                Stripe::setApiKey('sk_test_VmsSrI1HDHks7bBCky5SsvKl');

                try {
                    // On récupère le montant de la commande
                    $charge = Charge::create(array('amount' => $booking->getTotalPrice()*100, 'currency' => 'eur', 'source' => $paiement->getToken() ));

                    $booking->setToken($paiement->getToken());
                    $em = $this->getDoctrine()->getManager();
                    $em->persist($booking);
                    $em->flush();

                    // On définit le mail
                    $contenu = $this->renderView('TLABLouvreBundle:Ticket:email.html.twig', array(
                        'token' => $paiement->getToken()
                    ));


                    $mailer = $this->get('swiftmailer.mailer');

                    $message = (new Swift_Message('Musée du Louvre: Votre billet d\'entrée'))
                        ->setFrom(['becerra.mail@gmail.com' => 'Musée du Louvre'])
                        ->setTo([$booking->getEmail()])
                        ->setContentType('text/html')
                        ->setBody($contenu)
                    ;

                    $result = $mailer->send($message);


                    return $this->redirectToRoute('tlab_louvre_success');

                } catch (Card $error) {

                    // Si il y a eu une erreur on la renvoi en flashbag
                    $request->getSession()->getFlashBag()->add('paiement_error', $error->getMessage());
                }

                

            } else { // SI le formulaire n'est pas valide
                    // On ajoute un flashbag d'erreur
            }

        }



        return $this->render('TLABLouvreBundle:Booking:confirm.html.twig', [
            'booking'   => $booking,
            'form'   => $form->createView()
        ]);
    }

    public function successAction()
    {
        return $this->render('TLABLouvreBundle:Booking:success.html.twig', [
        ]);
    }
}

src/TLAB/LouvreBundle/Resources/views/Booking/booking.html.twig
{% extends "TLABLouvreBundle:Layout:base.html.twig" %}

{% block page_title %}Billeterie en ligne{% endblock %}

{% block page_body %}

    <div class="well">

        {{ form_start(form, {'attr': {'class': 'form'}}) }}

            <div class="row">
                <div class="col-12 col-lg-6">
                    <label for="booking_date" class="form-label">A quelle date souhaitez-vous réserver votre place ?</label>
                    <div class="input-group form-group">
                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                        {{ form_widget(form.date, {'attr': {'class': 'form-control form-control-lg'}}) }}
                    </div>
                    <div>
                        {% if form.date.vars.errors is not empty %}<div class="col-12 alert alert-danger">{{ form_errors(form.date) }}</div>{% endif %}
                        {% if errors is not empty %}<div class="col-12 alert alert-danger">{% for error in errors %}{{ error.message }}{% endfor %}</div>{% endif %}
                    </div>
                </div>

                <div class="col-12 col-lg-6">
                    <label for="booking_type" class="form-label">Type de réservation</label>
                    <div class="input-group form-group">
                        <span class="input-group-addon"><i class="fa fa-hourglass-half"></i></span>
                        {{ form_widget(form.type, {'attr': {'class': 'form-control form-control-lg '}}) }}
                    </div>
                    <div>
                        {% if form.type.vars.errors is not empty %}<div class="col-12 alert alert-danger">{{ form_errors(form.type) }}</div>{% endif %}
                    </div>
                </div>

                <div class="col-12">
                    <label for="booking_peoples" class="form-label">Liste des personnes</label>
                    <div class="input-group form-group">
                        <span class="input-group-addon"><i class="fa fa-users"></i></span>


                        <div class="row">
                            <div class="col-12">
                                <div class="bg-dark text-white peoples_head">
                                    <div class="col-12">
                                        <div class="row">

                                            <div class="col-12 col-lg-2 pt-2 pb-2">Prénom</div>
                                            <div class="col-12 col-lg-2 pt-2 pb-2">Nom</div>
                                            <div class="col-12 col-lg-2 pt-2 pb-2">Pays</div>
                                            <div class="col-12 col-lg-3 pt-2 pb-2">Date de naissance</div>
                                            <div class="col-10 col-lg-2 pt-2 pb-2">Tarif réduit</div>
                                            <div class="col-2 col-lg-1"></div>
                                        </div>
                                    </div>

                                </div>
                                {{ form_widget(form.peoples, {'attr': {'class': 'bg-white'}}) }}
                            </div>

                        </div>

                    </div>
                    <div>
                        {% if form.peoples.vars.errors is not empty %}<div class="col-12 alert alert-danger">{{ form_errors(form.peoples) }}</div>{% endif %}
                    </div>
                </div>

                <div class="col-12">
                    <div class="input-group form-group">
                        <span class="input-group-addon"><i class="fa fa-envelope-o"></i></span>
                        {{ form_widget(form.email, {'attr': {'class': 'form-control form-control-lg', 'placeholder': 'Adresse E-mail : example@contact.com'}}) }}
                    </div>
                    <div>
                        {% if form.email.vars.errors is not empty %}<div class="col-12 alert alert-danger">{{ form_errors(form.email) }}</div>{% endif %}
                    </div>
                </div>
            </div>









        {% if form.vars.errors is not empty %}<div class="col-12 alert alert-danger">{{ form_errors(form) }}</div>{% endif %}


        {{ form_widget(form.submit, {'attr': {'class': 'btn btn-primary btn-block'}}) }}

        {{ form_rest(form) }}
        {{ form_end(form) }}
    </div>

{% endblock %}

{% block js %}
    <script src="{{ asset('assets/js/booking.js') }}"></script>
{% endblock %}

src/TLAB/LouvreBundle/Resources/views/Booking/confirm.html.twig
{% extends "TLABLouvreBundle:Layout:base.html.twig" %}

{% block page_title %}Résumé de votre commande{% endblock %}

{% block page_body %}

    <div class="well">
        <div class="row">

            <div class="col-12">
                <table class="table table-bordered table-responsive bg-white">
                    <thead>
                        <tr>
                            <th>Date de réservation</th>
                            <th>Formule</th>
                            <th>Nombre de personnes</th>
                            <th>Email de contact</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>{{ booking.date|date('d/m/Y') }}</td>
                            <td>{{ booking.type==1 ? 'Journée Complète' : 'Demi-journée (A partir de 14H00)' }}</td>
                            <td>{{ booking.numberOfPeoples }}</td>
                            <td>{{ booking.email }}</td>
                        </tr>
                    </tbody>
                </table>
                <table class="table table-bordered table-responsive bg-white">
                    <thead>
                    <tr>
                        <th>Nom</th>
                        <th>Prénom</th>
                        <th>Date de naissance</th>
                        <th>Age</th>
                        <th>Pays</th>
                        <th>Tarif réduit</th>
                        <th>Prix HT</th>
                        <th>Prix TTC</th>
                    </tr>
                    </thead>
                    <tbody>

                    {% for people in booking.peoples %}
                        <tr>
                            <td>{{ people.lastname }}</td>
                            <td>{{ people.firstname }}</td>
                            <td>{{ people.birthday|date('d/m/Y') }}</td>
                            <td>{{ people.age }}</td>
                            <td>{{ people.country }}</td>
                            <td>{{ people.reducedPrice == 1 ? 'Oui' : 'Non' }}</td>
                            <td>{{ people.price - people.price*0.2 }}€</td>
                            <td>{{ people.price }}€</td>
                        </tr>
                    {% endfor %}

                    </tbody>

                    <thead>
                    <tr>
                        <th colspan="8">Prix Total : </th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td colspan="6"></td>
                        <td class="bg-light">{{ booking.totalPrice - booking.totalPrice*0.2 }}€</td>
                        <td class="bg-success text-white">{{ booking.totalPrice }}€</td>
                    </tr>
                    </tbody>
                </table>

                {% for message in app.session.flashbag.get('paiement_error') %}
                    <p class="alert alert-danger mb-2 mt-2">Erreur lors du paiement : {{ message }}</p>
                {% endfor %}
                
                <div class="btn-group w-100">
                    <a href="{{ path('tlab_louvre_edit_booking', {'id': booking.id}) }}" class="btn btn-light btn-block mt-2">Modifier la commande</a>
                    <button class="btn btn-success btn-block" data-toggle="modal" data-target="#stripe_paiement">Valider la commande</button>
                </div>

                {# Piament par stripe #}
                <div class="modal fade" id="stripe_paiement" tabindex="-1" role="dialog" aria-labelledby="stripe_paiement" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title">Informations de paiement</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">

                                {{ form_start(form, {'attr': {'class': 'form', 'id': 'stripe_form'}}) }}

                                <div class="form-group">

                                    <div class="form-group">
                                            {{ form_widget(form.token) }}
                                            {{ form_rest(form) }}
                                    </div>

                                    <div class="form-group">
                                        <div id="card-element" class="form-control">
                                        </div>
                                    </div>


                                    <!-- Used to display Element errors -->
                                    <div id="card-errors" role="alert"></div>
                                </div>

                                <input type="submit" value="Confirmer la commande" class="btn btn-block btn-primary">

                                {{ form_end(form) }}


                            </div>
                        </div>
                    </div>
                </div>


            </div>

        </div>
    </div>

{% endblock %}

{% block js %}
    <script src="https://js.stripe.com/v3/"></script>
    <script>
        var stripe = Stripe('pk_test_MjZUoMUoBaccqRZ17g40c2aA');
        var elements = stripe.elements();
        var card = elements.create('card');

        card.mount('#card-element');

        card.addEventListener('change', function(event) {
            var displayError = document.getElementById('card-errors');
            if (event.error) {
                displayError.textContent = event.error.message;
            } else {
                displayError.textContent = '';
            }
        });

        var form = document.getElementById('stripe_form');

        form.addEventListener('submit', function(event) {
            event.preventDefault();
            $('input[type="submit"]').attr('disabled', true);

            stripe.createToken(card).then(function(result) {
                if (result.error) {
                    // Inform the user if there was an error
                    var errorElement = document.getElementById('card-errors');
                    errorElement.textContent = result.error.message;
                } else {
                    // Send the token to your server
//                    stripe.TokenHandler(result.token);
                    console.log(result.token);

                    $('#tlab_louvrebundle_paiement_token').val(result.token.id);

                    $('#stripe_form').submit();
                }
            });
        });

    </script>
{% endblock %}

src/TLAB/LouvreBundle/Resources/views/Booking/payed.html.twig
{% extends "TLABLouvreBundle:Layout:base.html.twig" %}

{% block page_title %}Cette réservation a déja été payée{% endblock %}

{% block page_body %}

    <div class="well">
        <div class="row">
            <div class="col-12">

                
                <p class="text-center">Rendez-vous dans votre boîte mail pour récupérer votre tiquet</p>


            </div>

        </div>
    </div>

{% endblock %}

src/TLAB/LouvreBundle/Resources/views/Booking/success.html.twig
{% extends "TLABLouvreBundle:Layout:base.html.twig" %}

{% block page_title %}Votre billet vous a été envoyé par E-mail{% endblock %}

{% block page_body %}

    <div class="well">
        <div class="row">
            <div class="col-12">

                
                <p class="text-center">Merci de votre confiance et à très bientôt !</p>


            </div>

        </div>
    </div>

{% endblock %}

{% block js %}
    <script src="https://js.stripe.com/v3/"></script>
    <script>
        var stripe = Stripe('pk_test_MjZUoMUoBaccqRZ17g40c2aA');
        var elements = stripe.elements();
        var card = elements.create('card');

        card.mount('#card-element');

        card.addEventListener('change', function(event) {
            var displayError = document.getElementById('card-errors');
            if (event.error) {
                displayError.textContent = event.error.message;
            } else {
                displayError.textContent = '';
            }
        });

        var form = document.getElementById('stripe_form');

        form.addEventListener('submit', function(event) {
            event.preventDefault();
            $('input[type="submit"]').attr('disabled', true);

            stripe.createToken(card).then(function(result) {
                if (result.error) {
                    // Inform the user if there was an error
                    var errorElement = document.getElementById('card-errors');
                    errorElement.textContent = result.error.message;
                } else {
                    // Send the token to your server
//                    stripe.TokenHandler(result.token);
                    console.log(result.token);

                    $('#tlab_louvrebundle_paiement_token').val(result.token.id);

                    $('#stripe_form').submit();
                }
            });
        });

    </script>
{% endblock %}